### ISSUE TITLE
mask_isnobal = True throws error when using a netcdf topo

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/awsm#24]
line 102 of framework.py assumes the mask will be a file. But when we use a netcdf instead it is a property of the topo.nc file so when we use a netcdf it throws an error because cfg[topo][mask] = None.

**Comment by micah-prime** [comment]
We need to make a topo class for awsm where the dem, mask, and maybe roughness files are stored in memory. The get_topo_stats function from utils could be moved in here as well. This would simplify a lot of repeat logic around checking the dem and mask to see what the filetype is and reading them in multiple times
