### ISSUE TITLE
Equation C11 in snow.py is incorrect

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/awsm#29]
Per a conversation with @dannymarks, we determined that C11 in snow.py is not the correct version of the equation

            c11[ind] = (c_min + ((Tz - s_tsnow[ind]) * cfac)) + 1.0

but should be 
             c11 = exp(-0.046 * ((rho_ns * water) - 100.0))

Our tests will have to change too.

**Comment by micah-prime** [comment]
@micahjohnson150 this does not seem like an AWSM issue other than updating our tests which I think you did. Can I close this?

**Comment by micahjohnson150** [comment]
You are correct, this is addressed in smrf issues 72 which is now closed.

https://github.com/USDA-ARS-NWRC/smrf/issues/72
