### ISSUE TITLE
Make netcdf files more verbose

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/awsm#41]
@etrujil brought up that it would be helpful if the X and Y variables had a description of where in the cell it is referencing (lower left, middle, etc.). Additionally, we need to add in the projection information to the PySnobal output files. This is true for SMRF as well.

He also brought up that we should make the descriptions more detailed for the variables. The units could use some more description and the accumulation period (as in accumulated over the last 24 hrs, 1 hour) should be stated in the em file.

**Comment by micahjohnson150** [comment]
Roger.  Do we know how we are referencing cells? lol
