### ISSUE TITLE
non picklable dictionary

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/awsm#5]
When running multiple weather generator forecast runs, the copy of copy.deepcopy(self.config) errors out due to an attempt at parallel copying. This will need addressed to have a more robust config. (possibly addressed by adding a coreconfig and inicheck as this will eliminate the need for the function that calls deepcopy in the firs place)

**Comment by scotthavens** [comment]
Weather generator has been removed from AWSM, this will not exist outside of AWSM instead of within if it's still desired.
