### ISSUE TITLE
Directory names not created are not being printed in the log files

### ISSUE THREAD

**Issue by etrujil** [USDA-ARS-NWRC/awsm#54]
@micahjohnson150 @scotthavens 

Log files are missing the directory names for the folders that are not created because they already exists. The following line is logged:

"Directory --{}-- exists, not creating."

**Comment by scotthavens** [comment]
The writing of the log file on this [line](https://github.com/USDA-ARS-NWRC/awsm/blob/9e6de4bb1494c8ce861547548394131ad2555739/awsm/framework/framework.py#L675) shows that it's not having the path passed to the logger. There was an earlier log issue that this was most likely an attempt to fix, hence the `tmp_log` and not going to the logger directly.

```
self.tmp_log.append('Directory --{}-- exists, not creating.\n')
```
