### ISSUE TITLE
Travis Build Issues around new config and threading.

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/awsm#60]
Per my discovery during PR #58 while updating the smrf config options in awsm, we found that the test test base run in test_configurations.py would cause problems seemingly only on travis. 

It seemed to be associated with the following in the config file: 

- Setting threading to True
- Modeling less than 24 hours 
- And maybe make_nc = True

**Comment by scotthavens** [comment]
This hasn't happened recently and with the new SMRF package in #70, the travis build is completely different.
